### ISSUE TITLE
google place picker not working in IOS infinite search screens on search icon click

### ISSUE THREAD

**Issue by hariaravind10** [dacrystal/nativescript-google-place-picker#6]
Hi @dacrystal 

I was successfully get the google place in android, but ios i am not getting google place search option .......
and also i am getting android address not properly....please see the sample output below
"JS: {"nativePlace":{},"id":"ChIJ0ZqH66_6NToRQPIp3npxdP4","name":"Pizza Hut","address":"39 & 1","latitude":16.5025591,"longitude":80.64261139999999}
JS: 16.5025591
JS: 80.64261139999999
**JS: 39 & 1**    // ********see this is address i am getting in android*********** /////////
JS: Pizza Hut
JS: Camera changed: {"latitude":-33.85999989127037,"longitude":151.1999999731779,"zoom":8,"bearing":0,"tilt":0} false    "

// ios search image attached below  see for reference /////
![image](https://user-images.githubusercontent.com/34663118/47359447-6d586100-d6ea-11e8-8fc5-fe8c9e32e9d6.png)

**Comment by divyachandana** [comment]
Hi, @dacrystal 
Facing issue as above, 
Could not get address properly in **android**  
`{"nativePlace":{},"id":"ChIJ0ZqH66_6NToRQPIp3npxdP4","name":"Pizza Hut",
"address":"39 & 1","latitude":16.5025591,"longitude":80.64261139999999}`

google place picker ng-demo code working properly in IOS ... 
while integrating it in my project showing screen like above image,  going to the search screen again and again 

> `could not able to search places in IOS :( `

ill send you my project's `package.json` file if you want

**Comment by dacrystal** [comment]
Hi All, I have developed this plugin when I was working on a Nativescript-base project. During that time I belief the following versions were used:

```
Nativescript (3.0.*)
Ios | GooglePlaces (2.3.1)
Android | google-services:3.0.0  
```

Since that time, I belief many things have changed that break compatibilities from both sides; Nativescript and Google Service(places). Unfortunately, I can not help you in this as, currently, I'm no longer working on this technologies.
